name: Atama
version: '${project.version}'
main: atama.atama.AtamaMain
api-version: 1.19
authors: [ Elite_Watermelon ]
description: A plugin that allows the gaining of other players heads either with a command or by killing them
commands:
  skull:
    description: Lets an operator on the server grab the skull of another player
  redeem_skull:
    description: Lets the player redeem the skull they are holding in their hand